name: ${name}
description: A Minecraft interface to interact with and log activities on the UserStalker project
authors: [ Fulminazzo ]
version: '${version}'
main: ${group}.${name_lower}.${name}
api-version: '1.13'
website: https://github.com/fulminazzo/userstalker

commands:
  ${name_lower}:
    description: ${name} main command
    permission: ${name_lower}.command
    aliases: [ "users", "ustalker", "us" ]

permissions:
  ${name_lower}.command:
    description: Permission for /${name_lower} command
    default: op
  ${name_lower}.command.reload:
    description: Permission for /${name_lower} reload command
    default: op
  ${name_lower}.command.lookup:
    description: Permission for /${name_lower} lookup command
    default: op
  ${name_lower}.command.opengui:
    description: Permission for /${name_lower} opengui command
    default: op
  ${name_lower}.command.help:
    description: Permission for /${name_lower} help command
    default: op
  ${name_lower}.*:
    description: Wildcard permission
    ${name_lower}.command: true
    ${name_lower}.command.reload: true
    ${name_lower}.command.lookup: true
    ${name_lower}.command.opengui: true
    ${name_lower}.command.help: true
