# Name of the action
name: Publish on Remote Server

# Event to run on
on:
  workflow_run:
    workflows: [ "Automatic Release" ]
    types:
      - completed
    branches:
      - "master"
      - "main"

concurrency:
  group: publish
  cancel-in-progress: true

# Jobs that will execute
jobs:
  build:
    name: Setup Environment, Build JAR and Release JAR on remote server
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Copy JAR via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/libs/${{ github.event.repository.name }}.jar"
          target: "minecraft/plugins"
          strip_components: 2

      - name: Reload plugin in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |-
            screen -S minecraft -X stuff "plugman load userstalker-minecraft^M"
            screen -S minecraft -X stuff "plugman reload UserStalker^M"
