# Synchronizes the master branch with dev by pushing any commits on the former.
name: Sync master to dev

on:
  push:
    branches:
      - master

concurrency:
  group: sync-master-dev
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Update branches
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git checkout dev
          git merge origin/master --no-edit
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
